package com.ecommerce.multivendor.multivendor.domain;

public enum AccountStatus {

	PENDING_VERIFICATION,//ACCOUNT IS CREATED BUT NOT YET VERIFIED
	ATIVATE,             //ACCOUNT IS ACTIVATED AND IN GOOD STANDING
	SUSPENDED,           //ACCOUNT IS TEMPORARILY SUSPENDED, POSSIBLE DUE TO VIOLATIONS
	DEACTIVATED,         //ACCOUNT IS DEACTIVATED, USER MAY HAVE CHOSEN TO DEACRIVATE IT
	BANNED,              //ACCOUNT IS PERMANENTLY BANNED DUE TO SERVE VIOLATIONS
	CLOSED 
}
